name: Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the bug
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of jspec are you using?
      placeholder: "0.3.0"
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Minimal reproduction
      description: Provide a minimal code sample that reproduces the issue
      render: java
      placeholder: |
        Specification spec = ...;
        Map<String, Object> doc = ...;
        // What code causes the issue?

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Copy and paste any relevant log output
      render: shell

  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      options:
        - Java 21
        - Java 22
        - Java 23
        - Other
    validations:
      required: true